providers = ["nix", "docker"]

[phases.setup]
nixPkgs = ["nginx", "php", "phpPackages.composer", "phpPackages.fpm"]

[phases.build]
cmds = [
  "composer install --no-dev --optimize-autoloader",
  "php artisan config:cache",
  "php artisan route:cache",
  "php artisan view:cache"
]

[start]
cmd = "php-fpm -y ./nginx/php-fpm.conf && nginx -c /app/nginx/nginx.conf"
