[build]
builder = "heroku/buildpacks:20"
buildCommand = "composer install --no-dev --optimize-autoloader && php artisan config:cache && php artisan route:cache && php artisan view:cache && chmod -R 777 storage bootstrap/cache && echo 'OK' > public/health.php"

[deploy]
startCommand = "php-fpm -y ./nginx/php-fpm.conf && nginx -c /app/nginx/nginx.conf | tee /dev/stderr"
restartPolicyType = "ON_FAILURE"

[env]
LOG_CHANNEL = "stderr"