[build]
builder = "heroku/buildpacks:20"
buildCommand = "composer install --no-dev && chmod -R 777 storage bootstrap/cache"

[deploy]
startCommand = "php -S 0.0.0.0:8080 public/index.php"

[env]
APP_ENV="local"
APP_DEBUG="true"