[build]
builder = "heroku/buildpacks:20"
buildCommand = "composer install --no-dev --optimize-autoloader && php artisan config:cache && php artisan route:cache && php artisan view:cache && chmod -R 777 storage bootstrap/cache"

[deploy]
startCommand = "sh -c 'php-fpm -D && nginx -g \"daemon off;\"'"
restartPolicyType = "ON_FAILURE"

[env]
LOG_CHANNEL = "stderr"
APP_DEBUG = "false"