[build]
builder = "heroku/buildpacks:20"
buildCommand = "composer install && npm install && npm run build && chmod -R 777 storage bootstrap/cache"

[deploy]
startCommand = "sh -c 'php -v && php -m && php -i && php artisan serve --host=0.0.0.0 --port=8080'"

[env]
APP_ENV="local"
APP_DEBUG="true"