[build]
builder = "heroku/buildpacks:20"
buildCommand = "composer install && npm install && npm run build && chmod -R 775 storage bootstrap/cache"

[deploy]
startCommand = "sh -c 'php-fpm -y ./nginx/php-fpm.conf -d error_log=/dev/stderr && nginx -c /app/nginx/nginx.conf -g \"daemon off;\"'"

[env]
APP_ENV = "production"
APP_DEBUG = "true"
LOG_CHANNEL = "stderr"