[build]
builder = "heroku/buildpacks:20"
buildCommand = "composer install --no-dev --optimize-autoloader && php artisan config:cache && php artisan route:cache && php artisan view:cache"

[deploy]
startCommand = "php-fpm -y ./nginx/php-fpm.conf && nginx -c /app/nginx/nginx.conf"
restartPolicyType = "ON_FAILURE"